### ISSUE TITLE
Q-update issue

### ISSUE THREAD

**Issue by zhouzypaul** [camall3n/actgen#13]
https://github.com/camall3n/actgen/blob/cc05061ded2a83b542a9b602db6b7669f449ed1f/actgen/agents/DirectedQNet.py#L40-L46

@camall3n I can't seem to get q-update to work for some reason. I don't know why these 7 lines of code don't actually update the q-value (after the udpate `original_q_values` turn out to be exactly the same as `new_q_values`).

**Comment by camall3n** [comment]
Does `clone` give you a true copy, or just a second view into the same data?

**Comment by zhouzypaul** [comment]
`clone` gives a true copy (I've printed the tensor out and checked), although it changes the gradient function of the tensor from `AddmmBackward` to `CopySlices`.

The clone part is the same as how I used to do it before I refactored the code, so I think that should work

**Comment by zhouzypaul** [comment]
ah I know the problem: 
torch is doing sth weird when I did `q_target[0][a] = original_q_values[0][a] + delta_update`
it's fixed with `q_target[0][a] = float(original_q_values[0][a]) + delta_update`

Thanks for taking a look!

**Comment by zhouzypaul** [comment]
Is it valid to do multiple continuous updates with 
```
 for _ in range(n_updates): 
     self.optimizer.step() 
```

I tried to wrap the for loop around `loss` and `loss.backward()`, but that gave back some errors.

**Comment by camall3n** [comment]
Are you forgetting to call `zero_grad` in the loop? I'm not used to seeing multiple `step` calls outside of the normal `zero_grad`, `backward`, `step` sequence

**Comment by zhouzypaul** [comment]
when I call `zero_grad` in the loop, all q_delta's become 0. 

I've also tried placing the loop around L34-L46. That also works with the code, but don't give the same confusion matrix that is separated into blocks.

**Comment by camall3n** [comment]
I'm saying try
```python
self.train()
for _ in range(n_updates):
     self.optimizer.zero_grad()
     loss = compute_loss()
     loss.backward()
     self.optimizer.step() 
```

**Comment by zhouzypaul** [comment]
yea that's what I had in the first place, and it had an error:
`RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.
`

This can be solved by:
```
                self.eval()
                original_q_values = self.forward(s.float())  # q(s, a') for all a'
                q_target = original_q_values.detach().clone()
                q_target[0][a] = float(original_q_values[0][a]) + delta_update

                # perform n updates for q(s, a)
                self.train()
                for i in range(n_updates):
                    self.optimizer.zero_grad()
                    loss = torch.nn.functional.smooth_l1_loss(input=original_q_values, target=q_target)
                    if i == n_updates - 1:
                        loss.backward()
                    else:
                        loss.backward(retain_graph=True)
                    self.optimizer.step()
```
But this gets another error RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [256, 20]], which is output 0 of TBackward, is at version 3; expected version 2 instead. It looks like torch is not able to compute the gradient of `original_q_values`

**Comment by zhouzypaul** [comment]
Is it valid to just do this instead? 
```
self.hard_copy_from(baseline_qnet)

self.eval()
original_q_values = self.forward(s.float())  # q(s, a') for all a'

for _ in range(n_updates):
    # get original q-values & update target
    self.eval()
    original_q_values = self.forward(s.float())  # q(s, a') for all a'
    q_target = original_q_values.detach().clone()
    q_target[0][a] = float(original_q_values[0][a]) + delta_update

    # perform n updates for q(s, a)
    self.train()
    self.optimizer.zero_grad()
    loss = torch.nn.functional.smooth_l1_loss(input=original_q_values, target=q_target)
    loss.backward()
    self.optimizer.step()

self.eval()
new_q_values = self.forward(s.float())
q_delta[s_idx, a_idx, :] = new_q_values.detach().numpy()[0] - original_q_values.detach().numpy()[0]
```
This solves the problem of not calling `zero_grad` and `backward` in every iteration, and the code works.
I didn't call `.detach()` when creating `q_target` in my earlier code, and it might have created a problem, so I don't know if we should be expecting to see the confusion matrix that's separated into blocks.

**Comment by camall3n** [comment]
Any time you set `q_target` to the result of a computation, for example:
```python
q_target = original_q_values.detach().clone()
q_target[0][a] = float(original_q_values[0][a]) + delta_update
```
it causes the operations on the right hand side to be added to the computation graph. Here you detach the gradients in the first line, so nothing before that is added to the graph. However, the `clone`, the indexing `[0][a]`, the `float` cast, and the `+` operations will all be added to the graph, and any operations that created `delta_update` will be added recursively as well.

Generally this isn't what you want when you're creating a regression target; you want the gradients to be retained for the `original_q_values`, but not for the `q_target`. This is especially important if your targets are constructed using your inputs, as is the case here, since you don't usually want to backpropagate gradients through your inputs via multiple paths.

One easy way to avoid the issue is to always wrap the construction of your targets inside `with torch.no_grad()`:

```python
self.eval()
original_q_values = self.forward(s.float())  # q(s, a') for all a'
with torch.no_grad():
    q_target = original_q_values.detach().clone()
    q_target[0][a] = float(original_q_values[0][a]) + delta_update

# perform n updates for q(s, a)
self.train()
for i in range(n_updates):
    self.optimizer.zero_grad()
    loss = torch.nn.functional.smooth_l1_loss(input=original_q_values, target=q_target)
    if i == n_updates - 1:
        loss.backward()
    else:
        loss.backward(retain_graph=True)
    self.optimizer.step()
```

**Comment by zhouzypaul** [comment]
ah, I see where I was wrong. Thanks! 
The code above gave back some errors, probably because of some weirdness with `original_q_values`, so I went with the following, which I think makes the most sense 
```python
with torch.no_grad():
    original_q_values = self.forward(s.float())
    q_target = original_q_values.detach().clone()
    q_target[0][a] = float(original_q_values[0][a]) + delta_update

for i in range(n_updates):
    self.eval()
    current_q_vals = self.forward(s.float())  # q(s, a') for all a'

    # perform n updates for q(s, a)
    self.train()
    self.optimizer.zero_grad()
    loss = torch.nn.functional.smooth_l1_loss(input=current_q_vals, target=q_target)
    loss.backward()
    self.optimizer.step()
```

**Comment by camall3n** [comment]
Yes, okay! This makes a lot more sense.

One question I still have is why are you switching back and forth between `eval` and `train` modes? You can just set self.train() before the loop and leave it there the whole time.

**Comment by camall3n** [comment]
And for what it's worth, if the construction of `original_q_values` is wrapped in `torch.no_grad`, you don't need to `detach()` because there's no gradient info to begin with. You also probably don't need the `clone` either.

**Comment by zhouzypaul** [comment]
> Yes, okay! This makes a lot more sense.
> 
> One question I still have is why are you switching back and forth between `eval` and `train` modes? You can just set self.train() before the loop and leave it there the whole time.

Yea I will just set `self.train()` before the for loop. I'm not that familiar with how PyTorch works so I set `eval()`'s to make sure there's no training there. 

I'll also get rid of the `detach()`  for `original_q_values`. The `clone()` however, is still needed here, or else `q_target` is just a name that also points to `original_q_values`, and `q_target[0][a] = float(original_q_values[0][a]) + delta_update` will change the value of both.
