### ISSUE TITLE
return `G`

### ISSUE THREAD

**Issue by zhouzypaul** [camall3n/actgen#2]
https://github.com/camall3n/actgen/blob/04af9f46d576e68503b160d4d2e56183850853f0/actgen/train.py#L86

Is the return `G` usually not discounted by a constant factor in RL experiments?

**Comment by camall3n** [comment]
It usually is, that's correct. This technically shouldn't be called G. It's an artifact of copying code from elsewhere (Kavosh's repo to be precise, although I think there it may have made sense to say G). Here it's just the total episode reward.
